config/routes.rb
PharmaCC::Application.routes.draw do

  get "report/sell"

  get "report/user"

  get "report/product"

  get "report/provider"

  devise_for :users, :controllers => {:registrations => "users"} 
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :users

  resources :sells

  get "static_pages/home"
  get "static_pages/help"

  resources :products
  resources :providers
  resources :cities
  resources :states

  root :to => 'static_pages#home'
  
  match 'cities_json/:state_id', :controller =>'cities', :action => 'select_json'

end

app/models/sell.rb
class Sell < ActiveRecord::Base
  attr_accessible :products, :product_tokens, :user

  belongs_to :user

  has_many :sell_products
  has_many :products, :through => :sell_products

  accepts_nested_attributes_for :sell_products
  
  attr_reader :product_tokens
  
  def product_tokens=(id)
    self.product_ids = id.split(",")
  end

  def total
    t = 0.0
    products.each{ |p| t += p.price }
    t
  end

end

app/controllers/sells_controller.rb
class SellsController < ApplicationController

  load_and_authorize_resource
  # GET /sells
  # GET /sells.json
  def index
    @sells = Sell.all
  end

  # GET /sells/1
  # GET /sells/1.json
  def show
    @sell = Sell.find(params[:id])
  end

  # GET /sells/new
  # GET /sells/new.json
  def new
    @sell = Sell.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sell }
    end
  end

  # GET /sells/1/edit
  def edit
    @sell = Sell.find(params[:id])
  end

  # POST /sells
  # POST /sells.json
  def create
    @sell = current_user.sells.new(params[:sell])

    respond_to do |format|
      if @sell.save

        for product in @sell.products
          product.amount = product.amount - 1
          product.save!
        end

        format.html { redirect_to @sell, notice: 'Sell was successfully created.' }
        format.json { render json: @sell, status: :created, location: @sell }
      else
        format.html { render action: "new" }
        format.json { render json: @sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sells/1
  # PUT /sells/1.json
  def update
    @sell = Sell.find(params[:id])

    respond_to do |format|
      if @sell.update_attributes(params[:sell])
        format.html { redirect_to @sell, notice: 'Sell was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sells/1
  # DELETE /sells/1.json
  def destroy
    @sell = Sell.find(params[:id])
    @sell.destroy

    respond_to do |format|
      format.html { redirect_to sells_url }
      format.json { head :ok }
    end
  end
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/views/sells/_form.html.haml
= semantic_form_for @sell do |f| 
 
  = f.inputs do
    /= f.input :products, :as => :check_boxes, :collection => Product.all
    = f.input :product_tokens, :as => :string, :input_html => { "data-pre" => @sell.products.map(&:attributes).to_json }

  = f.buttons do 
    = f.commit_button "Concluir Venda"

app/views/sells/edit.html.erb
<h1>Editing sell</h1>

<%= render 'form' %>

<%= link_to 'Show', @sell %> |
<%= link_to 'Back', sells_path %>

app/views/sells/index.html.haml
%table{ :style => "width: 100%;" }
  %th{ :align => "center" }
    Gerência de Vendas

#sells_mng.has_a_datatable
  %table#sells
    %thead
      %tr
        %td
          %center
            Código
        %td
          %center
            Realizada em:
        - if (can? :edit, Sell) or (can? :destroy, Sell)
          %td
            %center
              Ações
    %tbody
      - @sells.each do |sell|
        - if can? :read, sell
          %tr
            %td
              = sell.id
            %td
              = sell.created_at.in_time_zone
            - if (can? :edit, sell) or (can? :destroy, sell)
              %td
                - if can? :edit, sell
                  = link_to (image_tag "edit.png", :alt => "editar cadastro"), edit_sell_path(sell)
                \&nbsp;
                - if can? :destroy, sell
                  = link_to (image_tag "remove.png", :alt => "editar cadastro"), sell, :confirm => 'Deseja mesmo excluir esta Venda?', :method => :delete

= render :partial => 'layouts/mng_buttons', :locals => { :new_path => new_sell_path, :what => Sell }

app/views/sells/new.html.erb
<h1>Nova venda</h1>

<%= render 'form' %>

<%= link_to 'Voltar', sells_path %>

app/views/sells/show.html.haml
-#%p#notice= notice
-##nota
#nota
  /%h3 Nota fiscal
  %table#users
    %thead
      %tr
        %td
          %center
            Código
        %td
          %center
            Produto
        %td
          %center
            Preço
    %tbody
      - for p in @sell.products
        %tr
          %td
            = p.code.to_s
          %td
            = p.name
          %td
            = p.price.to_s
        %tr
    %tfoot
      %tr
        %td
          Total
        %td
          \-
        %td
          = @sell.total
      %tr

  = link_to 'Editar os dados cadastrados', edit_sell_path(@sell)
  |
  \#{link_to 'Continuar', sells_path}