config/routes.rb
PharmaCC::Application.routes.draw do

  get "report/sell"

  get "report/user"

  get "report/product"

  get "report/provider"

  devise_for :users, :controllers => {:registrations => "users"} 
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :users

  resources :sells

  get "static_pages/home"
  get "static_pages/help"

  resources :products
  resources :providers
  resources :cities
  resources :states

  root :to => 'static_pages#home'
  
  match 'cities_json/:state_id', :controller =>'cities', :action => 'select_json'

end

app/views/layouts/_footer.html.haml
.footer
  %p
    %span
      - if user_signed_in?
        = "Olá " + current_user.name
        = link_to "(Logout)", logout_path
      - else
        Nenhum usuário logado.
#design
  Powered by: PharmaCC Systems

app/views/layouts/_form_buttons.html.haml
%p{ :align => "center" }
  %input{ :type => "submit", :value => what }
  \&nbsp;&nbsp;&nbsp;
  %input{ :type => "reset", :value => "Limpar" }
  \&nbsp;&nbsp;&nbsp;
  %input{ :type => "button", :value => "Gerenciar " + who, :onclick => "location.href='" + where + "'" }

app/views/layouts/_header.html.haml
.header
  %p.logo
    = link_to root_path do
      = image_tag "logo.png", :alt => "PharmaCC"
      PharmaCC
    Sistema de gerenciamento de farmácias
  .header-menu
    - if user_signed_in?
      %ul.menu
        %li.page_item
          = link_to root_path do
            %span
              %span
                Início
        %li.page_item
          %a{ :href => "#" }
            %span
              %span
                Gerenciar
          %ul
            %li
              - if can? :read, User
                = link_to 'Usuários', users_path
            %li
              - if can? :read, Product
                = link_to 'Produtos', products_path
            %li
              - if can? :read, Provider
                = link_to 'Fornecedores', providers_path
        %li.page_item
          %a{ :href => "#" }
            %span
              %span
                Cadastrar
          %ul
            %li
              = link_to new_sell_path do 
                Venda
            %li
              = link_to new_product_path do 
                Produto
            %li
              = link_to new_provider_path do
                Fornecedor
            %li
              = link_to new_user_path do
                Usuário
        %li.page_item
          %a{ :href => "#" }
            %span
              %span
                Relatórios
          %ul
            %li
              = link_to report_product_path do 
                Produtos
            %li
              = link_to report_sell_path do
                Vendas
            %li
              = link_to report_user_path do
                Usuários
        %li.page_item
          = link_to static_pages_help_path do 
            %span
              %span
                Ajuda
        %li.page_item
          = link_to logout_path do
            %span
              %span
                Sair

app/views/layouts/_mng_buttons.html.haml
%p{ :align => "center" }
  - if can? :create, what
    %input{ :type => "button", :value => "Cadastrar novo", :onclick => "location.href='" + new_path + "'" }
  \&nbsp;&nbsp;&nbsp;
  %input{ :type => "button", :value => "Menu principal", :onclick => "location.href='" + root_path + "'" }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      PharmaCC | Sistema de gerenciamento de farmácias
    = stylesheet_link_tag    "application", "token-input"
    = javascript_include_tag "application", "jquery.tokeninput"
    = csrf_meta_tags
  %body
    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"
    = render 'layouts/header'
    .content
      .main{ :align => "center" }
        = yield
    = render 'layouts/footer'